#!/usr/bin/env python3
"""Regenerate the dwmapi.dll dynamic-wrapper sources.

Why this exists: dwmapi.dll is a loader-hijack proxy placed next to steam.exe.
The old implementation used `#pragma comment(linker, "/EXPORT:X=DWMAPI.X")`
forwarders. When our DLL is the first module named "dwmapi" in the process,
the loader resolves the bare forwarder target "DWMAPI" back to ourselves,
forming a self-forward loop. Every importer (SteamUI.dll, steamclient64.dll,
...) then fails with ERROR_BAD_EXE_FORMAT (193) and steam.exe reports
"Failed to load steamui.dll". Older Steam builds masked this because
something else pulled in System32\\dwmapi.dll first; beta 1788989629 changed
the load order and every cold start broke.

The fix: a true dynamic wrapper (same pattern as src/xinput1_4/). The DLL
exports real stub functions that tail-jump (`jmp qword ptr [target]`, which
preserves all registers/stack for any signature) to the real System32 copy
loaded by absolute path via GetSystemDirectoryA. Full-path loads never hit
the self-resolution problem because full paths bypass bare-name search.

Regenerate after a Windows update shifts dwmapi ordinals:
    python3 tools/generate_dwmapi_wrapper.py

Trim to the proven subset (see SUBSET_EVIDENCE below):
    python3 tools/generate_dwmapi_wrapper.py --only DwmGetWindowAttribute

Outputs (all in src/dwmapi/):
    dwmapi_tramp.asm  - MASM x64 tail-jump stubs + fallback (returns 0/S_OK)
    dwmapi.def        - export table with current System32 ordinals
    dwmapi.cpp        - loader (resolves all targets) + injection gate
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "src" / "dwmapi"

# Subset evidence (measured 2026-09-10 with dumpbin /IMPORTS over every
# *.exe/*.dll under C:\Program Files (x86)\Steam, excluding steamapps):
#   - DwmGetWindowAttribute <- SteamUI.dll, steamclient.dll, steamclient64.dll
#   - DwmSetWindowAttribute, DwmExtendFrameIntoClientArea <- bin\vgui2_s.dll
#   - libcef/steamwebhelper delay-load 5 funcs but run in their own dir and
#     always bind System32 directly; never touch the proxy.
# Scoping rule: once the proxy is THE dwmapi in steam.exe's process, EVERY
# later-loaded module (including bin\*.dll) binds its dwmapi imports to us.
# So the subset must cover the whole process, not just steam.exe's imports.
# A missed export fails closed ("Could not load module"), so if Steam ever
# imports more, re-run without --only. Lesson 2026-09-10: a hand-rolled PE
# parser silently skipped vgui2_s.dll and a 1-export trim broke startup.
DEFAULT_ONLY = ["DwmGetWindowAttribute", "DwmSetWindowAttribute",
                "DwmExtendFrameIntoClientArea"]


def read_system_exports() -> tuple[list[tuple[int, str]], list[int]]:
    system32 = Path(
        subprocess.check_output(
            ["powershell", "-NoProfile", "-Command",
             "[System.Environment]::GetFolderPath('System')"],
            text=True,
        ).strip()
    ) / "dwmapi.dll"
    import pefile  # noqa: PLC0415

    pe = pefile.PE(str(system32))
    named: list[tuple[int, str]] = []
    ordonly: list[int] = []
    for sym in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if sym.name:
            named.append((sym.ordinal, sym.name.decode()))
        else:
            ordonly.append(sym.ordinal)
    named.sort()
    ordonly.sort()
    return named, ordonly


def asm_safe(name: str) -> str:
    return name  # all dwmapi names are valid MASM identifiers


def stub_sym(ordinal: int, name: str | None) -> str:
    return asm_safe(name) if name else f"DwmOrd{ordinal}"


def target_sym(ordinal: int, name: str | None) -> str:
    return f"g_Target_{name}" if name else f"g_Target_Ord{ordinal}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", nargs="*", default=None,
                    help="export names and/or ordinals to keep; default: proven subset; "
                         "'ALL' keeps everything")
    args = ap.parse_args()

    named, ordonly = read_system_exports()
    entries = [(o, n) for o, n in named] + [(o, None) for o in ordonly]
    entries.sort()
    print(f"system dwmapi: {len(named)} named + {len(ordonly)} ordinal-only = {len(entries)}")

    keep = args.only if args.only is not None else DEFAULT_ONLY
    if keep != ["ALL"]:
        want = set(keep)
        entries = [(o, n) for o, n in entries
                   if (n in want) or (str(o) in want)]
        missing = [k for k in want
                   if k not in {n for _, n in entries} and k not in {str(o) for o, _ in entries}]
        if missing:
            return f"subset entries not found in system dwmapi: {missing}"
        print(f"subset: keeping {len(entries)} export(s)")

    asm: list[str] = [
        "; GENERATED by tools/generate_dwmapi_wrapper.py - do not hand-edit.",
        "; Tail-jump stubs forwarding to the real System32\\dwmapi.dll.",
        "; A pure `jmp [target]` preserves registers/stack for ANY signature",
        "; (x64 caller cleans the stack; results travel in rax/xmm0).",
        "; Unresolved targets default to DwmFallback (returns 0).",
        "",
        ".code",
        "DwmFallback PROC",
        "  xor eax, eax",
        "  ret",
        "DwmFallback ENDP",
        "",
        ".data",
    ]
    for ordinal, name in entries:
        asm.append(f"PUBLIC {target_sym(ordinal, name)}")
        asm.append(f"{target_sym(ordinal, name)} DQ DwmFallback")
    asm += ["", ".code"]
    for ordinal, name in entries:
        stub = stub_sym(ordinal, name)
        asm.append(f"PUBLIC {stub}")
        asm.append(f"{stub} PROC")
        asm.append(f"  jmp QWORD PTR [{target_sym(ordinal, name)}]")
        asm.append(f"{stub} ENDP")
    asm.append("END")
    (OUT_DIR / "dwmapi_tramp.asm").write_text("\n".join(asm) + "\n")

    banker = [f'; GENERATED by tools/generate_dwmapi_wrapper.py - do not hand-edit.{chr(10)}LIBRARY "dwmapi"',
              "EXPORTS"]
    for ordinal, name in entries:
        if name:
            banker.append(f"    {name} @{ordinal}")
        else:
            banker.append(f"    DwmOrd{ordinal} @{ordinal} NONAME")
    (OUT_DIR / "dwmapi.def").write_text("\n".join(banker) + "\n")

    cpp: list[str] = [
        "// GENERATED by tools/generate_dwmapi_wrapper.py - do not hand-edit.",
        "// dwmapi.dll HiJack - true dynamic wrapper (see script header for why).",
        "// Export stubs live in dwmapi_tramp.asm; this file resolves their",
        "// targets to the real System32 copy and injects OpenSteamTool.dll.",
        "",
        "#include <windows.h>",
        "#include <cstring>",
        "#include <string>",
        "",
        "static HMODULE g_hRealDwmapi = nullptr;",
        "",
    ]
    for ordinal, name in entries:
        cpp.append(f'extern "C" void* {target_sym(ordinal, name)};')
    cpp += [
        "",
        "struct DwmExportEntry { LPCSTR id; void** slot; };",
        "",
        "static const DwmExportEntry kDwmExports[] = {",
    ]
    for ordinal, name in entries:
        ident = f'"{name}"' if name else f"(LPCSTR){ordinal}"
        cpp.append(f"    {{ {ident}, (void**)&{target_sym(ordinal, name)} }},")
    cpp += [
        "};",
        "",
        "static void LoadRealDwmapi() {",
        "    if (g_hRealDwmapi) return;",
        "",
        "    char sysDir[MAX_PATH];",
        "    if (!GetSystemDirectoryA(sysDir, MAX_PATH)) return;",
        "    std::string realPath = std::string(sysDir) + \"\\\\dwmapi.dll\";",
        "",
        "    // Full-path load: bypasses bare-name search, so this can never",
        "    // resolve back to our own proxy next to steam.exe.",
        "    g_hRealDwmapi = LoadLibraryExA(realPath.c_str(), NULL,",
        "                                   LOAD_WITH_ALTERED_SEARCH_PATH);",
        "    if (!g_hRealDwmapi) return;",
        "",
        "    for (const auto& e : kDwmExports) {",
        "        if (FARPROC p = GetProcAddress(g_hRealDwmapi, e.id))",
        "            *e.slot = (void*)p;",
        "    }",
        "}",
        "",
        "// Only inject when the host process is steam.exe (case-insensitive).",
        "// LoadLibraryA itself guarantees that OpenSteamTool.dll's DllMain",
        "// runs at most once per process, so multiple hijack DLLs can safely",
        "// call this without additional synchronisation.",
        "BOOL OpenSteamToolLoad()",
        "{",
        "    char exePath[MAX_PATH];",
        "    if (GetModuleFileNameA(NULL, exePath, MAX_PATH))",
        "    {",
        "        const char* exeName = strrchr(exePath, '\\\\');",
        "        exeName = exeName ? exeName + 1 : exePath;",
        "        if (_stricmp(exeName, \"steam.exe\") != 0)",
        "            return TRUE;   // not Steam - proxy only, don't inject",
        "    }",
        "    return LoadLibraryA(\"OpenSteamTool.dll\") != NULL;",
        "}",
        "",
        "",
        "BOOL APIENTRY DllMain(HMODULE hModule, DWORD dwReason, PVOID pvReserved)",
        "{",
        "    switch (dwReason)",
        "    {",
        "    case DLL_PROCESS_ATTACH:",
        "        {",
        "            DisableThreadLibraryCalls(hModule);",
        "            LoadRealDwmapi();",
        "            if ( !OpenSteamToolLoad() )",
        "                return FALSE;",
        "            break;",
        "        }",
        "    case DLL_THREAD_ATTACH:",
        "    case DLL_THREAD_DETACH:",
        "    case DLL_PROCESS_DETACH:",
        "        break;",
        "    }",
        "    return TRUE;",
        "}",
        "",
    ]
    (OUT_DIR / "dwmapi.cpp").write_text("\n".join(cpp))
    print(f"wrote {OUT_DIR / 'dwmapi_tramp.asm'}")
    print(f"wrote {OUT_DIR / 'dwmapi.def'}")
    print(f"wrote {OUT_DIR / 'dwmapi.cpp'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
