// GENERATED by tools/generate_dwmapi_wrapper.py - do not hand-edit.
// dwmapi.dll HiJack - true dynamic wrapper (see script header for why).
// Export stubs live in dwmapi_tramp.asm; this file resolves their
// targets to the real System32 copy and injects OpenSteamTool.dll.

#include <windows.h>
#include <cstring>
#include <string>

static HMODULE g_hRealDwmapi = nullptr;

extern "C" void* g_Target_DwmExtendFrameIntoClientArea;
extern "C" void* g_Target_DwmGetWindowAttribute;
extern "C" void* g_Target_DwmSetWindowAttribute;

struct DwmExportEntry { LPCSTR id; void** slot; };

static const DwmExportEntry kDwmExports[] = {
    { "DwmExtendFrameIntoClientArea", (void**)&g_Target_DwmExtendFrameIntoClientArea },
    { "DwmGetWindowAttribute", (void**)&g_Target_DwmGetWindowAttribute },
    { "DwmSetWindowAttribute", (void**)&g_Target_DwmSetWindowAttribute },
};

static void LoadRealDwmapi() {
    if (g_hRealDwmapi) return;

    char sysDir[MAX_PATH];
    if (!GetSystemDirectoryA(sysDir, MAX_PATH)) return;
    std::string realPath = std::string(sysDir) + "\\dwmapi.dll";

    // Full-path load: bypasses bare-name search, so this can never
    // resolve back to our own proxy next to steam.exe.
    g_hRealDwmapi = LoadLibraryExA(realPath.c_str(), NULL,
                                   LOAD_WITH_ALTERED_SEARCH_PATH);
    if (!g_hRealDwmapi) return;

    for (const auto& e : kDwmExports) {
        if (FARPROC p = GetProcAddress(g_hRealDwmapi, e.id))
            *e.slot = (void*)p;
    }
}

// Only inject when the host process is steam.exe (case-insensitive).
// LoadLibraryA itself guarantees that OpenSteamTool.dll's DllMain
// runs at most once per process, so multiple hijack DLLs can safely
// call this without additional synchronisation.
BOOL OpenSteamToolLoad()
{
    char exePath[MAX_PATH];
    if (GetModuleFileNameA(NULL, exePath, MAX_PATH))
    {
        const char* exeName = strrchr(exePath, '\\');
        exeName = exeName ? exeName + 1 : exePath;
        if (_stricmp(exeName, "steam.exe") != 0)
            return TRUE;   // not Steam - proxy only, don't inject
    }
    return LoadLibraryA("OpenSteamTool.dll") != NULL;
}


BOOL APIENTRY DllMain(HMODULE hModule, DWORD dwReason, PVOID pvReserved)
{
    switch (dwReason)
    {
    case DLL_PROCESS_ATTACH:
        {
            DisableThreadLibraryCalls(hModule);
            LoadRealDwmapi();
            if ( !OpenSteamToolLoad() )
                return FALSE;
            break;
        }
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
