; GENERATED by tools/generate_dwmapi_wrapper.py - do not hand-edit.
; Tail-jump stubs forwarding to the real System32\dwmapi.dll.
; A pure `jmp [target]` preserves registers/stack for ANY signature
; (x64 caller cleans the stack; results travel in rax/xmm0).
; Unresolved targets default to DwmFallback (returns 0).

.code
DwmFallback PROC
  xor eax, eax
  ret
DwmFallback ENDP

.data
PUBLIC g_Target_DwmExtendFrameIntoClientArea
g_Target_DwmExtendFrameIntoClientArea DQ DwmFallback
PUBLIC g_Target_DwmGetWindowAttribute
g_Target_DwmGetWindowAttribute DQ DwmFallback
PUBLIC g_Target_DwmSetWindowAttribute
g_Target_DwmSetWindowAttribute DQ DwmFallback

.code
PUBLIC DwmExtendFrameIntoClientArea
DwmExtendFrameIntoClientArea PROC
  jmp QWORD PTR [g_Target_DwmExtendFrameIntoClientArea]
DwmExtendFrameIntoClientArea ENDP
PUBLIC DwmGetWindowAttribute
DwmGetWindowAttribute PROC
  jmp QWORD PTR [g_Target_DwmGetWindowAttribute]
DwmGetWindowAttribute ENDP
PUBLIC DwmSetWindowAttribute
DwmSetWindowAttribute PROC
  jmp QWORD PTR [g_Target_DwmSetWindowAttribute]
DwmSetWindowAttribute ENDP
END
